# Generated by Django 4.2.9 on 2024-02-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='\\img\\gallery\\project-2.jpg', upload_to='media'),
        ),
    ]
