# Generated by Django 4.2.9 on 2024-02-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualifications',
            field=models.TextField(default='None'),
        ),
    ]
